### ISSUE TITLE
cleanup npm scripts

### ISSUE THREAD

**Issue by jdalton** [taylor1791/lodash-custom-restangular#1]
I think npm scripts will auto detect bins so in your command you can use `lodash include=...` instead of the path to the bin.

**Comment by taylor1791** [comment]
Thanks for taking the time to look at this. Commit b046e85172 takes thesse suggestions into consideration. If nothing comes up in the next couple of days, I'll publish a new version of the package. If there is any other feedback, feel free to reopen the issue.
